version: 2
jobs:
   build:
      docker:
         - image: node:8

      working_directory: ~/repo

      steps:
         - checkout

         - restore_cache:
            keys:
               - cache-{{ .Branch }}-{{ checksum "package.json" }}
               - cache-{{ .Branch }}
               - cache-master-{{ checksum "package.json" }}
               - cache-master

         - run:
            name: Install dependencies
            command: yarn

         - run:
            name: Test
            command: yarn test

         - save_cache:
            key: cache-{{ .Branch }}-{{ checksum "package.json" }}
            paths:
               - node_modules
